export const PROJECT_ACTIONS = {
    POST_PROJECT: "POST_PROJECT",
    GATHER_PROJECT: "GATHER_PROJECT",
    POST_REQUEST_START: "POST_REQUEST_START",
    POST_REQUEST_DONE: "POST_REQUEST_DONE",
    POST_PROJECT_FAILED: "POST_PROJECT_FAILED",
    REQUEST_START: "REQUEST_START",
    REQUEST_DONE: "REQUEST_DONE",
    GET_PROJECTS: "GET_PROJECTS",
    GET_PROJECTS_START: "GET_PROJECTS_START",
    GET_PROJECTS_DONE: "GET_PROJECTS_DONE",
    GET_PROJECTS_SET: "GET_PROJECTS_SET",
    GET_PROJECTS_FAILED: "GET_PROJECTS_FAILED",
    GET_USER_PROJECT: "GET_USER_PROJECT",
    GET_USER_PROJECT_START: "GET_USER_PROJECT_START",
    GET_USER_PROJECT_DONE: "GET_USER_PROJECT_DONE",
    GET_USER_PROJECT_SET: "GET_USER_PROJECT_SET",
    GET_USER_PROJECT_FAILED: "GET_USER_PROJECT_FAILED",
    EDIT_PROJECT: "EDIT_PROJECT",
    GATHER_EDITED_PROJECT: "GATHER_EDITED_PROJECT",
    REQUEST_EDIT_START: "REQUEST_EDIT_START",
    REQUEST_EDIT_DONE: "REQUEST_EDIT_DONE",
    EDIT_PROJECT_FAILED: "EDIT_PROJECT_FAILED",
}

export const triggerPost = (project) => ({
    type: PROJECT_ACTIONS.POST_PROJECT,
    payload: {
      project,
    },
  });

  export const fetchProjects = () => {
    return {type: PROJECT_ACTIONS.GET_PROJECTS};
  };

  export const fetchUserProject = () => ({
    type: PROJECT_ACTIONS.GET_USER_PROJECT,
  });

  export const triggerPut = (project) => ({    
    type:PROJECT_ACTIONS.EDIT_PROJECT,
    payload: {
      project,
    },
  });
